/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as CriarRouteImport } from './routes/criar'
import { Route as MeusJogosRouteImport } from './routes/meus-jogos'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PartidaIdRouteImport } from './routes/partida.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarRoute = CriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusJogosRoute = MeusJogosRouteImport.update({
  id: '/meus-jogos',
  path: '/meus-jogos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PartidaIdRoute = PartidaIdRouteImport.update({
  id: '/partida/$id',
  path: '/partida/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/criar': typeof CriarRoute
  '/meus-jogos': typeof MeusJogosRoute
  '/perfil': typeof PerfilRoute
  '/partida/$id': typeof PartidaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/criar': typeof CriarRoute
  '/meus-jogos': typeof MeusJogosRoute
  '/perfil': typeof PerfilRoute
  '/partida/$id': typeof PartidaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/criar': typeof CriarRoute
  '/meus-jogos': typeof MeusJogosRoute
  '/perfil': typeof PerfilRoute
  '/partida/$id': typeof PartidaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/buscar'
    | '/criar'
    | '/meus-jogos'
    | '/perfil'
    | '/partida/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/buscar'
    | '/criar'
    | '/meus-jogos'
    | '/perfil'
    | '/partida/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/buscar'
    | '/criar'
    | '/meus-jogos'
    | '/perfil'
    | '/partida/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BuscarRoute: typeof BuscarRoute
  CriarRoute: typeof CriarRoute
  MeusJogosRoute: typeof MeusJogosRoute
  PerfilRoute: typeof PerfilRoute
  PartidaIdRoute: typeof PartidaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar': {
      id: '/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof CriarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-jogos': {
      id: '/meus-jogos'
      path: '/meus-jogos'
      fullPath: '/meus-jogos'
      preLoaderRoute: typeof MeusJogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partida/$id': {
      id: '/partida/$id'
      path: '/partida/$id'
      fullPath: '/partida/$id'
      preLoaderRoute: typeof PartidaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BuscarRoute: BuscarRoute,
  CriarRoute: CriarRoute,
  MeusJogosRoute: MeusJogosRoute,
  PerfilRoute: PerfilRoute,
  PartidaIdRoute: PartidaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
