platform :ios, '18.2'

target 'iosApp' do
  use_frameworks! :linkage => :static
  pod 'FirebaseCore'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseFunctions'
  pod 'Firebase/Messaging'
  pod 'FirebaseAnalytics'
  pod 'FirebaseCrashlytics'
  pod 'GoogleSignIn'
  pod 'PurchasesHybridCommon', '17.55.1'
  pod 'RevenueCat', '5.67.1'
end
