package com.walcker.games.strings

internal data class CreateMatchStrings(
    val title: String,
    val subtitle: String,
    val sectionVenue: String,
    val sectionWhen: String,
    val sectionDetails: String,
    val venueNameLabel: String,
    val venueNamePlaceholder: String,
    val sportLabel: String,
    val neighborhoodLabel: String,
    val neighborhoodPlaceholder: String,
    val cityLabel: String,
    val cityPlaceholder: String,
    val addressLabel: String,
    val addressPlaceholder: String,
    val pickLocationHint: String,
    val resolvingLocation: String,
    val locationNotResolved: String,
    val dateLabel: String,
    val datePlaceholder: String,
    val timeLabel: String,
    val timePlaceholder: String,
    val durationLabel: String,
    val durationValue: (minutes: Int) -> String,
    val playersLabel: String,
    val playersValue: (count: Int) -> String,
    val priceLabel: String,
    val pricePlaceholder: String,
    val priceHelper: String,
    val submit: String,
    val validationError: String,
    val genericError: String,
    val notLoggedIn: String,
    val success: String,
    val confirm: String,
    val cancel: String,
)

internal val createMatchStringsPt = CreateMatchStrings(
    title = "Criar partida",
    subtitle = "Preencha os dados da sua partida",
    sectionVenue = "Onde vai ser",
    sectionWhen = "Quando vai ser",
    sectionDetails = "Detalhes da partida",
    venueNameLabel = "Nome da quadra",
    venueNamePlaceholder = "Ex: Arena Central",
    sportLabel = "Esporte",
    neighborhoodLabel = "Bairro",
    neighborhoodPlaceholder = "Ex: Bela Vista",
    cityLabel = "Cidade",
    cityPlaceholder = "Ex: São Paulo",
    addressLabel = "Endereço",
    addressPlaceholder = "Rua, número",
    pickLocationHint = "Arraste o mapa até o local da partida",
    resolvingLocation = "Identificando o endereço…",
    locationNotResolved = "Não foi possível identificar o endereço deste ponto.",
    dateLabel = "Data",
    datePlaceholder = "Escolher data",
    timeLabel = "Horário",
    timePlaceholder = "Escolher horário",
    durationLabel = "Duração",
    durationValue = { minutes -> "$minutes minutos" },
    playersLabel = "Total de jogadores",
    playersValue = { count -> "$count jogadores" },
    priceLabel = "Preço por jogador",
    pricePlaceholder = "Ex: 25,00",
    priceHelper = "Deixe em branco se a partida for gratuita.",
    submit = "Criar e publicar",
    validationError = "Preencha todos os campos obrigatórios para publicar.",
    genericError = "Não foi possível criar a partida. Tente de novo.",
    notLoggedIn = "Entre na sua conta para criar uma partida.",
    success = "Partida criada com sucesso!",
    confirm = "OK",
    cancel = "Cancelar",
)

internal val createMatchStringsEn = CreateMatchStrings(
    title = "Create match",
    subtitle = "Fill in your match details",
    sectionVenue = "Where it happens",
    sectionWhen = "When it happens",
    sectionDetails = "Match details",
    venueNameLabel = "Venue name",
    venueNamePlaceholder = "e.g. Central Arena",
    sportLabel = "Sport",
    neighborhoodLabel = "Neighborhood",
    neighborhoodPlaceholder = "e.g. Downtown",
    cityLabel = "City",
    cityPlaceholder = "e.g. São Paulo",
    addressLabel = "Address",
    addressPlaceholder = "Street, number",
    pickLocationHint = "Drag the map to the match location",
    resolvingLocation = "Looking up the address…",
    locationNotResolved = "Could not identify the address for this point.",
    dateLabel = "Date",
    datePlaceholder = "Pick a date",
    timeLabel = "Time",
    timePlaceholder = "Pick a time",
    durationLabel = "Duration",
    durationValue = { minutes -> "$minutes minutes" },
    playersLabel = "Total players",
    playersValue = { count -> "$count players" },
    priceLabel = "Price per player",
    pricePlaceholder = "e.g. 25.00",
    priceHelper = "Leave it empty if the match is free.",
    submit = "Create and publish",
    validationError = "Fill in every required field to publish.",
    genericError = "Could not create the match. Please try again.",
    notLoggedIn = "Sign in to create a match.",
    success = "Match created successfully!",
    confirm = "OK",
    cancel = "Cancel",
)
