package com.walcker.games.strings

internal data class CreateMatchStrings(
    val title: String,
    val subtitle: String,
    val venueNameLabel: String,
    val venueNamePlaceholder: String,
    val sportLabel: String,
    val neighborhoodLabel: String,
    val neighborhoodPlaceholder: String,
    val cityLabel: String,
    val cityPlaceholder: String,
    val addressLabel: String,
    val addressPlaceholder: String,
    val dateLabel: String,
    val timeLabel: String,
    val durationLabel: String,
    val playersLabel: String,
    val priceLabel: String,
    val pricePlaceholder: String,
    val submit: String,
    val submitting: String,
    val validationError: String,
    val genericError: String,
    val success: String,
)

internal val createMatchStringsPt = CreateMatchStrings(
    title = "Criar partida",
    subtitle = "Preencha os dados da sua partida",
    venueNameLabel = "Nome da quadra",
    venueNamePlaceholder = "Ex: Arena Central",
    sportLabel = "Esporte",
    neighborhoodLabel = "Bairro",
    neighborhoodPlaceholder = "Ex: Bela Vista",
    cityLabel = "Cidade",
    cityPlaceholder = "Ex: São Paulo",
    addressLabel = "Endereço",
    addressPlaceholder = "Rua, número",
    dateLabel = "Data",
    timeLabel = "Horário",
    durationLabel = "Duração",
    playersLabel = "Total de jogadores",
    priceLabel = "Preço por jogador",
    pricePlaceholder = "Ex: 25,00",
    submit = "Criar e Publicar",
    submitting = "Publicando...",
    validationError = "Preencha todos os campos obrigatórios.",
    genericError = "Não foi possível criar a partida.",
    success = "Partida criada com sucesso!",
)

internal val createMatchStringsEn = CreateMatchStrings(
    title = "Create match",
    subtitle = "Fill in your match details",
    venueNameLabel = "Venue name",
    venueNamePlaceholder = "e.g. Central Arena",
    sportLabel = "Sport",
    neighborhoodLabel = "Neighborhood",
    neighborhoodPlaceholder = "e.g. Downtown",
    cityLabel = "City",
    cityPlaceholder = "e.g. São Paulo",
    addressLabel = "Address",
    addressPlaceholder = "Street, number",
    dateLabel = "Date",
    timeLabel = "Time",
    durationLabel = "Duration",
    playersLabel = "Total players",
    priceLabel = "Price per player",
    pricePlaceholder = "e.g. 25.00",
    submit = "Create and Publish",
    submitting = "Publishing...",
    validationError = "Please fill in all required fields.",
    genericError = "Could not create the match.",
    success = "Match created successfully!",
)
