package com.walcker.games.strings

internal data class ManageMatchStrings(
    val title: String,
    val loadingLabel: String,
    val backContentDescription: String,
    val dismissContentDescription: String,
    val retry: String,
    val notFound: String,
    val editMatch: String,
    val cancelMatch: String,
    val cancelMatchSeries: String,
    val cancelDialogTitle: String,
    val cancelDialogBody: String,
    val cancelDialogConfirm: String,
    val cancelSeriesDialogTitle: String,
    val cancelSeriesDialogBody: String,
    val cancelSeriesDialogConfirm: String,
    val dialogDismiss: String,
    val cancelSuccess: String,
    val cancelAlreadyCancelled: String,
    val cancelError: String,
    val cancelSeriesSuccess: String,
    val cancelSeriesError: String,
    val teamsSaveError: String,
    val ratePlayersSection: String,
    val ratePlayersEmpty: String,
    val confirmedTag: String,
    val paidTag: String,
    val rateAction: String,
    val editRatingAction: String,
    val ratingsCount: (Int) -> String,
)

internal val manageMatchStringsEn =
    ManageMatchStrings(
        title = "Manage match",
        loadingLabel = "Loading…",
        backContentDescription = "Back",
        dismissContentDescription = "Dismiss",
        retry = "Try again",
        notFound = "Match not found.",
        editMatch = "Edit match",
        cancelMatch = "Cancel match",
        cancelMatchSeries = "Cancel recurrence",
        cancelDialogTitle = "Cancel this match?",
        cancelDialogBody = "Everyone who joined will be notified.",
        cancelDialogConfirm = "Cancel match",
        cancelSeriesDialogTitle = "Cancel the recurrence?",
        cancelSeriesDialogBody =
            "This match stays as is. No new matches will be created for this recurring series.",
        cancelSeriesDialogConfirm = "Cancel recurrence",
        dialogDismiss = "Keep it",
        cancelSuccess = "Match cancelled",
        cancelAlreadyCancelled = "This match was already cancelled",
        cancelError = "Couldn't cancel the match. Try again.",
        cancelSeriesSuccess = "Recurrence cancelled. No new matches will be created.",
        cancelSeriesError = "Couldn't cancel the recurrence. Try again.",
        teamsSaveError = "Couldn't save the teams. Try again.",
        ratePlayersSection = "Rate players",
        ratePlayersEmpty = "Nobody to rate yet.",
        confirmedTag = "Confirmed",
        paidTag = "Paid",
        rateAction = "Rate",
        editRatingAction = "Edit rating",
        ratingsCount = { n -> if (n == 1) "1 review" else "$n reviews" },
    )

internal val manageMatchStringsPt =
    ManageMatchStrings(
        title = "Organizar partida",
        loadingLabel = "Carregando…",
        backContentDescription = "Voltar",
        dismissContentDescription = "Dispensar",
        retry = "Tentar de novo",
        notFound = "Partida não encontrada.",
        editMatch = "Editar partida",
        cancelMatch = "Cancelar partida",
        cancelMatchSeries = "Cancelar recorrência",
        cancelDialogTitle = "Cancelar a partida?",
        cancelDialogBody = "Todo mundo que entrou será avisado.",
        cancelDialogConfirm = "Cancelar partida",
        cancelSeriesDialogTitle = "Cancelar a recorrência?",
        cancelSeriesDialogBody =
            "Esta partida continua como está. Nenhuma nova partida será criada dessa série recorrente.",
        cancelSeriesDialogConfirm = "Cancelar recorrência",
        dialogDismiss = "Manter",
        cancelSuccess = "Partida cancelada",
        cancelAlreadyCancelled = "Partida já foi cancelada",
        cancelError = "Não foi possível cancelar a partida. Tente de novo.",
        cancelSeriesSuccess = "Recorrência cancelada. Nenhuma nova partida será criada.",
        cancelSeriesError = "Não foi possível cancelar a recorrência. Tente de novo.",
        teamsSaveError = "Não foi possível salvar os times. Tente de novo.",
        ratePlayersSection = "Avaliar jogadores",
        ratePlayersEmpty = "Ainda não tem quem avaliar.",
        confirmedTag = "Confirmado",
        paidTag = "Pago",
        rateAction = "Avaliar",
        editRatingAction = "Editar avaliação",
        ratingsCount = { n -> if (n == 1) "1 avaliação" else "$n avaliações" },
    )
