package com.walcker.games.strings

internal data class ManageMatchStrings(
    val title: String,
    val loadingLabel: String,
    val backContentDescription: String,
    val dismissContentDescription: String,
    val retry: String,
    val notFound: String,
    val editMatch: String,
    val cancelMatch: String,
    val cancelMatchSeries: String,
    val statusOpen: String,
    val statusFull: String,
    val statusInProgress: String,
    val statusFinished: String,
    val statusCancelled: String,
    val confirmedCountLabel: (Int) -> String,
    val cancelDialogTitle: String,
    val cancelDialogBody: String,
    val cancelDialogConfirm: String,
    val cancelSeriesDialogTitle: String,
    val cancelSeriesDialogBody: String,
    val cancelSeriesDialogConfirm: String,
    val dialogDismiss: String,
    val cancelSuccess: String,
    val cancelAlreadyCancelled: String,
    val cancelError: String,
    val cancelSeriesSuccess: String,
    val cancelSeriesError: String,
    val teamsSaveError: String,
    val teamsSectionTitle: String,
    val teamsCountLabel: String,
    val teamsPlayersPerTeamLabel: String,
    val teamsPlayersPerTeamValue: (count: Int) -> String,
    val teamsCapacityLabel: (current: Int, capacity: Int) -> String,
    val teamsShuffleAction: String,
    val teamsReshuffleAction: String,
    val teamsUnassignedSection: String,
    val teamsEmptySection: String,
    val teamLabel: (index: Int) -> String,
    val teamsMoveToMenuTitle: String,
    val teamsMoveToOption: (teamLabel: String) -> String,
    val teamsDragHandleContentDescription: String,
    val skillRatingUnrated: String,
    val skillRatingValue: (rating: Float) -> String,
    val skillRatingMenuTitle: String,
    val skillRatingContentDescription: String,
    val skillRatingError: String,
    val skillRatingDialogClose: String,
    val ratePlayersSection: String,
    val ratePlayersEmpty: String,
    val confirmedTag: String,
    val paidTag: String,
    val rateAction: String,
    val editRatingAction: String,
    val ratingsCount: (Int) -> String,
    val managePlayersAction: String,
    val nextMatchLabel: String,
    val editMatchContentDescription: String,
    val statConfirmedLabel: String,
    val statVipsLabel: String,
    val statTeamsLabel: String,
    val managePlayersTitle: String,
    val gameListSection: String,
    val waitlistSection: String,
    val waitlistEmpty: String,
    val waitlistPositionLabel: (position: Int) -> String,
    val vipAction: String,
    val vipRemoveAction: String,
    val confirmWaitlistedAction: String,
    val banAction: String,
    val banConfirmTitle: (name: String) -> String,
    val banConfirmMessage: String,
    val banConfirmButton: String,
    val banCancelButton: String,
    val vipSuccessMessage: (name: String) -> String,
    val vipRemovedMessage: (name: String) -> String,
    val confirmWaitlistedSuccessMessage: (name: String) -> String,
    val banSuccessMessage: (name: String) -> String,
    val vipError: String,
    val confirmWaitlistedError: String,
    val banError: String,
)

internal val manageMatchStringsEn =
    ManageMatchStrings(
        title = "Manage match",
        loadingLabel = "Loading…",
        backContentDescription = "Back",
        dismissContentDescription = "Dismiss",
        retry = "Try again",
        notFound = "Match not found.",
        editMatch = "Edit match",
        cancelMatch = "Cancel match",
        cancelMatchSeries = "Cancel recurrence",
        statusOpen = "Open",
        statusFull = "Full",
        statusInProgress = "In progress",
        statusFinished = "Finished",
        statusCancelled = "Cancelled",
        confirmedCountLabel = { n -> "$n confirmed" },
        cancelDialogTitle = "Cancel this match?",
        cancelDialogBody = "Everyone who joined will be notified.",
        cancelDialogConfirm = "Cancel match",
        cancelSeriesDialogTitle = "Cancel the recurrence?",
        cancelSeriesDialogBody =
            "This match stays as is. No new matches will be created for this recurring series.",
        cancelSeriesDialogConfirm = "Cancel recurrence",
        dialogDismiss = "Keep it",
        cancelSuccess = "Match cancelled",
        cancelAlreadyCancelled = "This match was already cancelled",
        cancelError = "Couldn't cancel the match. Try again.",
        cancelSeriesSuccess = "Recurrence cancelled. No new matches will be created.",
        cancelSeriesError = "Couldn't cancel the recurrence. Try again.",
        teamsSaveError = "Couldn't save the teams. Try again.",
        teamsSectionTitle = "Shuffle teams",
        teamsCountLabel = "Number of teams",
        teamsPlayersPerTeamLabel = "Players per team",
        teamsPlayersPerTeamValue = { count -> "$count players per team" },
        teamsCapacityLabel = { current, capacity -> "$current/$capacity players" },
        teamsShuffleAction = "Shuffle teams",
        teamsReshuffleAction = "Shuffle again",
        teamsUnassignedSection = "No team yet",
        teamsEmptySection = "No players",
        teamLabel = { index -> "Team ${('A' + index)}" },
        teamsMoveToMenuTitle = "Move to",
        teamsMoveToOption = { teamLabel -> "Move to $teamLabel" },
        teamsDragHandleContentDescription = "Drag handle",
        skillRatingUnrated = "Rate skill",
        skillRatingValue = { rating -> "$rating" },
        skillRatingMenuTitle = "Skill rating",
        skillRatingContentDescription = "Skill rating",
        skillRatingError = "Couldn't save the skill rating. Try again.",
        skillRatingDialogClose = "Close",
        ratePlayersSection = "Rate players",
        ratePlayersEmpty = "Nobody to rate yet.",
        confirmedTag = "Confirmed",
        paidTag = "Paid",
        rateAction = "Rate",
        editRatingAction = "Edit rating",
        ratingsCount = { n -> if (n == 1) "1 review" else "$n reviews" },
        managePlayersAction = "Manage players",
        nextMatchLabel = "Next match",
        editMatchContentDescription = "Edit match",
        statConfirmedLabel = "Confirmed",
        statVipsLabel = "VIPs",
        statTeamsLabel = "Teams",
        managePlayersTitle = "Manage players",
        gameListSection = "Game list",
        waitlistSection = "Waitlist",
        waitlistEmpty = "Nobody waiting.",
        waitlistPositionLabel = { position -> "Waiting · #$position" },
        vipAction = "Mark as VIP",
        vipRemoveAction = "Remove VIP",
        confirmWaitlistedAction = "Add to game list",
        banAction = "Ban from match",
        banConfirmTitle = { name -> "Ban $name?" },
        banConfirmMessage = "They won't be able to join this match again.",
        banConfirmButton = "Ban",
        banCancelButton = "Cancel",
        vipSuccessMessage = { name -> "$name is now VIP" },
        vipRemovedMessage = { name -> "$name is no longer VIP" },
        confirmWaitlistedSuccessMessage = { name -> "$name added to the game list" },
        banSuccessMessage = { name -> "$name banned from this match" },
        vipError = "Couldn't update VIP status. Try again.",
        confirmWaitlistedError = "Couldn't add the player to the game list. Try again.",
        banError = "Couldn't ban the player. Try again.",
    )

internal val manageMatchStringsPt =
    ManageMatchStrings(
        title = "Organizar partida",
        loadingLabel = "Carregando…",
        backContentDescription = "Voltar",
        dismissContentDescription = "Dispensar",
        retry = "Tentar de novo",
        notFound = "Partida não encontrada.",
        editMatch = "Editar partida",
        cancelMatch = "Cancelar partida",
        cancelMatchSeries = "Cancelar recorrência",
        statusOpen = "Aberta",
        statusFull = "Lotada",
        statusInProgress = "Em andamento",
        statusFinished = "Encerrada",
        statusCancelled = "Cancelada",
        confirmedCountLabel = { n -> "$n confirmados" },
        cancelDialogTitle = "Cancelar a partida?",
        cancelDialogBody = "Todo mundo que entrou será avisado.",
        cancelDialogConfirm = "Cancelar partida",
        cancelSeriesDialogTitle = "Cancelar a recorrência?",
        cancelSeriesDialogBody =
            "Esta partida continua como está. Nenhuma nova partida será criada dessa série recorrente.",
        cancelSeriesDialogConfirm = "Cancelar recorrência",
        dialogDismiss = "Manter",
        cancelSuccess = "Partida cancelada",
        cancelAlreadyCancelled = "Partida já foi cancelada",
        cancelError = "Não foi possível cancelar a partida. Tente de novo.",
        cancelSeriesSuccess = "Recorrência cancelada. Nenhuma nova partida será criada.",
        cancelSeriesError = "Não foi possível cancelar a recorrência. Tente de novo.",
        teamsSaveError = "Não foi possível salvar os times. Tente de novo.",
        teamsSectionTitle = "Sortear times",
        teamsCountLabel = "Quantidade de times",
        teamsPlayersPerTeamLabel = "Jogadores por equipe",
        teamsPlayersPerTeamValue = { count -> "$count jogadores por equipe" },
        teamsCapacityLabel = { current, capacity -> "$current/$capacity jogadores" },
        teamsShuffleAction = "Sortear times",
        teamsReshuffleAction = "Sortear de novo",
        teamsUnassignedSection = "Sem time",
        teamsEmptySection = "Nenhum jogador",
        teamLabel = { index -> "Time ${('A' + index)}" },
        teamsMoveToMenuTitle = "Mover para",
        teamsMoveToOption = { teamLabel -> "Mover para o $teamLabel" },
        teamsDragHandleContentDescription = "Alça de arraste",
        skillRatingUnrated = "Avaliar habilidade",
        skillRatingValue = { rating -> "$rating" },
        skillRatingMenuTitle = "Nota de habilidade",
        skillRatingContentDescription = "Nota de habilidade",
        skillRatingError = "Não foi possível salvar a nota de habilidade. Tente de novo.",
        skillRatingDialogClose = "Fechar",
        ratePlayersSection = "Avaliar jogadores",
        ratePlayersEmpty = "Ainda não tem quem avaliar.",
        confirmedTag = "Confirmado",
        paidTag = "Pago",
        rateAction = "Avaliar",
        editRatingAction = "Editar avaliação",
        ratingsCount = { n -> if (n == 1) "1 avaliação" else "$n avaliações" },
        managePlayersAction = "Gerenciar jogadores",
        nextMatchLabel = "Próxima partida",
        editMatchContentDescription = "Editar partida",
        statConfirmedLabel = "Confirmados",
        statVipsLabel = "VIPs",
        statTeamsLabel = "Times",
        managePlayersTitle = "Gerenciar jogadores",
        gameListSection = "Lista do jogo",
        waitlistSection = "Lista de espera",
        waitlistEmpty = "Ninguém esperando.",
        waitlistPositionLabel = { position -> "Esperando · #$position" },
        vipAction = "Marcar como VIP",
        vipRemoveAction = "Remover VIP",
        confirmWaitlistedAction = "Adicionar à lista do jogo",
        banAction = "Banir da partida",
        banConfirmTitle = { name -> "Banir $name?" },
        banConfirmMessage = "A pessoa não vai poder entrar de novo nessa partida.",
        banConfirmButton = "Banir",
        banCancelButton = "Cancelar",
        vipSuccessMessage = { name -> "$name agora é VIP" },
        vipRemovedMessage = { name -> "$name não é mais VIP" },
        confirmWaitlistedSuccessMessage = { name -> "$name adicionado à lista do jogo" },
        banSuccessMessage = { name -> "$name banido dessa partida" },
        vipError = "Não foi possível atualizar o status de VIP. Tente de novo.",
        confirmWaitlistedError = "Não foi possível adicionar à lista do jogo. Tente de novo.",
        banError = "Não foi possível banir o jogador. Tente de novo.",
    )
