package com.walcker.games.strings

internal data class MatchDetailStrings(
    val title: String,
    val loadingLabel: String,
    val backContentDescription: String,
    val dismissContentDescription: String,
    val organizedBy: (name: String) -> String,
    val rateMatchAction: String,
    val rateMatchSheetTitle: String,
    val matchRatingSubmitSuccess: String,
    val matchRatingAlreadyRated: String,
    val matchRatingSubmitError: String,
    val durationLabel: String,
    val durationValue: (Int) -> String,
    val priceLabel: String,
    val freePrice: String,
    val statusOpen: String,
    val statusFull: String,
    val statusFinished: String,
    val statusCancelled: String,
    val participants: String,
    val confirmedOf: (confirmed: Int, total: Int) -> String,
    val openSlotsRemaining: (Int) -> String,
    val noSlotsRemaining: String,
    val slotsBadge: (Int) -> String,
    val confirmedSection: (Int) -> String,
    val waitlistSection: (Int) -> String,
    val yourStatusConfirmedTitle: String,
    val yourStatusConfirmedExplanation: String,
    val yourStatusWaitlistTitle: (position: Int) -> String,
    val yourStatusWaitlistExplanation: String,
    val teamLabel: (index: Int) -> String,
    val yourTeamLabel: (teamLabel: String) -> String,
    val rateOrganizerAction: String,
    val rateOrganizerSheetTitle: String,
    val organizerRatingSubmitSuccess: String,
    val joinMatch: String,
    val joinWaitlist: String,
    val joiningWaitlistLabel: String,
    val matchClosed: String,
    val leaveMatch: String,
    val participateAction: String,
    val manageMatchAction: String,
    val promotedFromWaitlist: String,
    val retry: String,
    val notFound: String,
    val leaveDialogTitle: String,
    val leaveDialogBody: String,
    val leaveDialogConfirm: String,
    val dialogDismiss: String,
    val joinWaitlistSuccess: (position: Int) -> String,
    val joinAlreadyJoined: String,
    val joinError: String,
    val leaveSuccess: String,
    val leaveError: String,
    val loadError: String,
    val statusChangedToFull: String,
    val statusChangedToFinished: String,
    val statusChangedToCancelled: String,
    val unknownMatchTitle: String,
    val openLocationTitle: String,
    val openInGoogleMaps: String,
    val openInWaze: String,
    val openLocationCancel: String,
    val shareContentDescription: String,
    val shareSubject: (sport: String) -> String,
    val shareMessage: (
        sport: String,
        dayLabel: String,
        timeRange: String,
        venueName: String,
        address: String,
        joinLink: String,
    ) -> String,
)

internal val matchDetailStringsEn =
    MatchDetailStrings(
        title = "Match details",
        loadingLabel = "Loading the match…",
        backContentDescription = "Back",
        dismissContentDescription = "Dismiss",
        organizedBy = { name -> "Organised by $name" },
        rateMatchAction = "Rate this match",
        rateMatchSheetTitle = "How was the match?",
        matchRatingSubmitSuccess = "Thanks for your review!",
        matchRatingAlreadyRated = "You already rated this match.",
        matchRatingSubmitError = "Could not send your review. Please try again.",
        durationLabel = "Duration",
        durationValue = { min -> "$min min" },
        priceLabel = "Price",
        freePrice = "Free",
        statusOpen = "Open",
        statusFull = "Full",
        statusFinished = "Finished",
        statusCancelled = "Cancelled",
        participants = "Players",
        confirmedOf = { confirmed, total -> "$confirmed / $total confirmed" },
        openSlotsRemaining = { n -> if (n == 1) "1 slot left" else "$n slots left" },
        noSlotsRemaining = "No slots left",
        slotsBadge = { open ->
            when (open) {
                0 -> "Full"
                1 -> "1 slot"
                else -> "$open slots"
            }
        },
        confirmedSection = { n -> "Confirmed ($n)" },
        waitlistSection = { n -> "Waitlist ($n)" },
        yourStatusConfirmedTitle = "You're confirmed",
        yourStatusConfirmedExplanation = "Your slot in this match is guaranteed.",
        yourStatusWaitlistTitle = { pos -> "You're on the waitlist (position #$pos)" },
        yourStatusWaitlistExplanation = "You'll move up automatically if someone leaves before it starts.",
        teamLabel = { index -> "Team ${('A' + index)}" },
        yourTeamLabel = { teamLabel -> "You're on $teamLabel" },
        rateOrganizerAction = "Rate organizer",
        rateOrganizerSheetTitle = "How was your experience with the organizer?",
        organizerRatingSubmitSuccess = "Thanks for your review!",
        joinMatch = "Take my slot",
        joinWaitlist = "Join the waitlist",
        joiningWaitlistLabel = "Joining the waitlist…",
        matchClosed = "Match is over",
        leaveMatch = "Leave",
        participateAction = "Participate",
        manageMatchAction = "Manage match",
        promotedFromWaitlist = "You moved up from the waitlist!",
        retry = "Try again",
        notFound = "Match not found.",
        leaveDialogTitle = "Leave this match?",
        leaveDialogBody = "Your slot goes to the next player in the queue.",
        leaveDialogConfirm = "Leave",
        dialogDismiss = "Keep it",
        joinWaitlistSuccess = { pos -> "You're on the waitlist (position #$pos)" },
        joinAlreadyJoined = "You're already in this match",
        joinError = "Couldn't join the match. Try again.",
        leaveSuccess = "You left the match",
        leaveError = "Couldn't leave the match. Try again.",
        loadError = "Couldn't load the match. Try again.",
        statusChangedToFull = "Match is full 🔴 New joins go to the waitlist.",
        statusChangedToFinished = "Match is over ✓",
        statusChangedToCancelled = "This match was cancelled ✕",
        unknownMatchTitle = "Match",
        openLocationTitle = "Open location in",
        openInGoogleMaps = "Google Maps",
        openInWaze = "Waze",
        openLocationCancel = "Cancel",
        shareContentDescription = "Share match",
        shareSubject = { sport -> "$sport match" },
        shareMessage = { sport, dayLabel, timeRange, venueName, address, joinLink ->
            "Want to play? Join this $sport match with me!\n\n" +
                "📅 $dayLabel at $timeRange\n" +
                "📍 $venueName, $address\n\n" +
                "Tap to open in JoinPlay:\n$joinLink"
        },
    )

internal val matchDetailStringsPt =
    MatchDetailStrings(
        title = "Detalhes da partida",
        loadingLabel = "Carregando a partida…",
        backContentDescription = "Voltar",
        dismissContentDescription = "Dispensar",
        organizedBy = { name -> "Organizada por $name" },
        rateMatchAction = "Avaliar a partida",
        rateMatchSheetTitle = "Como foi a partida?",
        matchRatingSubmitSuccess = "Valeu pela avaliação!",
        matchRatingAlreadyRated = "Você já avaliou essa partida.",
        matchRatingSubmitError = "Não foi possível enviar sua avaliação. Tente de novo.",
        durationLabel = "Duração",
        durationValue = { min -> "$min min" },
        priceLabel = "Preço",
        freePrice = "Grátis",
        statusOpen = "Aberta",
        statusFull = "Lotada",
        statusFinished = "Encerrada",
        statusCancelled = "Cancelada",
        participants = "Participantes",
        confirmedOf = { confirmed, total -> "$confirmed / $total confirmados" },
        openSlotsRemaining = { n -> if (n == 1) "1 vaga restante" else "$n vagas restantes" },
        noSlotsRemaining = "Sem vagas",
        slotsBadge = { open ->
            when (open) {
                0 -> "Lotado"
                1 -> "1 vaga"
                else -> "$open vagas"
            }
        },
        confirmedSection = { n -> "Confirmados ($n)" },
        waitlistSection = { n -> "Fila de espera ($n)" },
        yourStatusConfirmedTitle = "Você está confirmado",
        yourStatusConfirmedExplanation = "Sua vaga nessa partida está garantida.",
        yourStatusWaitlistTitle = { pos -> "Você está na fila de espera (posição #$pos)" },
        yourStatusWaitlistExplanation = "Você entra automaticamente se alguém sair antes do início.",
        teamLabel = { index -> "Time ${('A' + index)}" },
        yourTeamLabel = { teamLabel -> "Você está no $teamLabel" },
        rateOrganizerAction = "Avaliar organizador",
        rateOrganizerSheetTitle = "Como foi a experiência com o organizador?",
        organizerRatingSubmitSuccess = "Valeu pela avaliação!",
        joinMatch = "Garantir minha vaga",
        joinWaitlist = "Entrar na fila de espera",
        joiningWaitlistLabel = "Entrando na fila de espera…",
        matchClosed = "Partida encerrada",
        leaveMatch = "Sair",
        participateAction = "Participar",
        manageMatchAction = "Organizar partida",
        promotedFromWaitlist = "Você foi promovido da fila!",
        retry = "Tentar de novo",
        notFound = "Partida não encontrada.",
        leaveDialogTitle = "Sair da partida?",
        leaveDialogBody = "Sua vaga vai para o próximo da fila.",
        leaveDialogConfirm = "Sair",
        dialogDismiss = "Manter",
        joinWaitlistSuccess = { pos -> "Você foi adicionado à fila de espera (posição #$pos)" },
        joinAlreadyJoined = "Você já é participante desta partida",
        joinError = "Não foi possível entrar na partida. Tente de novo.",
        leaveSuccess = "Você saiu da partida",
        leaveError = "Não foi possível sair da partida. Tente de novo.",
        loadError = "Não foi possível carregar a partida. Tente de novo.",
        statusChangedToFull = "Partida lotada! 🔴 Novas entradas serão na fila de espera.",
        statusChangedToFinished = "Partida encerrada ✓",
        statusChangedToCancelled = "Partida foi cancelada ✕",
        unknownMatchTitle = "Partida",
        openLocationTitle = "Abrir localização em",
        openInGoogleMaps = "Google Maps",
        openInWaze = "Waze",
        openLocationCancel = "Cancelar",
        shareContentDescription = "Compartilhar partida",
        shareSubject = { sport -> "Partida de $sport" },
        shareMessage = { sport, dayLabel, timeRange, venueName, address, joinLink ->
            "Bora jogar? Entra nessa partida de $sport comigo!\n\n" +
                "📅 $dayLabel às $timeRange\n" +
                "📍 $venueName, $address\n\n" +
                "Toque pra abrir no JoinPlay:\n$joinLink"
        },
    )
