package com.walcker.games.strings

internal data class PlayerProfileStrings(
    val title: String,
    val loadingLabel: String,
    val statsOrganized: String,
    val statsParticipated: String,
    val statsRating: String,
    val accountSettings: String,
    val loadingError: String,
    val availabilityTitle: String,
    val availabilityOnDescription: String,
    val availabilityOffDescription: String,
    val availabilityError: String,
    val ratingsReceived: String,
    val ratingsCount: (Int) -> String,
    val ratingContentDescription: (Float) -> String,
    val settings: String,
    val logout: String,
    val noRatingYet: String,
    val visitorMessage: String,
    val visitorSupportingText: String,
    val visitorCta: String,
    val availableUntilTonightLabel: String,
    val sportsPreferenceTitle: String,
    val sportsPreferenceError: String,
    val nextMatchSection: String,
    val viewPublicProfileAction: String,
    val fallbackAccountName: String,
)

internal val playerProfileStringsPt =
    PlayerProfileStrings(
        title = "Meu perfil",
        loadingLabel = "Carregando seu perfil…",
        statsOrganized = "Organizadas",
        statsParticipated = "Participadas",
        statsRating = "Nota média",
        accountSettings = "Configurações de conta",
        loadingError = "Erro ao carregar perfil.",
        availabilityTitle = "Estou disponível para jogar",
        availabilityOnDescription = "Você recebe aviso quando abrir partida perto de você.",
        availabilityOffDescription = "Você não recebe aviso de partida nova.",
        availabilityError = "Não foi possível mudar sua disponibilidade. Tente de novo.",
        ratingsReceived = "Avaliações recebidas",
        ratingsCount = { n -> if (n == 1) "1 avaliação" else "$n avaliações" },
        ratingContentDescription = { value -> "Nota $value de 5" },
        settings = "Configurações",
        logout = "Sair da conta",
        noRatingYet = "—",
        visitorMessage = "Entre para ver seu perfil",
        visitorSupportingText = "Suas partidas, avaliações e disponibilidade aparecem aqui depois que você entra.",
        visitorCta = "Entrar",
        availableUntilTonightLabel = "Só por hoje",
        sportsPreferenceTitle = "Esportes que eu jogo",
        sportsPreferenceError = "Não foi possível salvar seus esportes. Tente de novo.",
        nextMatchSection = "Próxima partida",
        viewPublicProfileAction = "Ver como outros jogadores me veem",
        fallbackAccountName = "Jogador",
    )

internal val playerProfileStringsEn =
    PlayerProfileStrings(
        title = "My profile",
        loadingLabel = "Loading your profile…",
        statsOrganized = "Organised",
        statsParticipated = "Played",
        statsRating = "Rating",
        accountSettings = "Account settings",
        loadingError = "Error loading profile.",
        availabilityTitle = "I'm available to play",
        availabilityOnDescription = "You'll be notified when a match opens near you.",
        availabilityOffDescription = "You won't be notified about new matches.",
        availabilityError = "Could not change your availability. Please try again.",
        ratingsReceived = "Ratings received",
        ratingsCount = { n -> if (n == 1) "1 rating" else "$n ratings" },
        ratingContentDescription = { value -> "Rated $value out of 5" },
        settings = "Settings",
        logout = "Log out",
        noRatingYet = "—",
        visitorMessage = "Sign in to see your profile",
        visitorSupportingText = "Your matches, ratings and availability show up here once you sign in.",
        visitorCta = "Sign in",
        availableUntilTonightLabel = "Just for today",
        sportsPreferenceTitle = "Sports I play",
        sportsPreferenceError = "Couldn't save your sports. Please try again.",
        nextMatchSection = "Next match",
        viewPublicProfileAction = "See how other players see you",
        fallbackAccountName = "Player",
    )
