package com.walcker.games.strings

internal data class PlayerProfileStrings(
    val title: String,
    val loadingLabel: String,
    val statsMatches: String,
    val statsParticipated: String,
    val statsReviews: String,
    val statsRating: String,
    val notificationsContentDescription: String,
    val loadingError: String,
    val availabilityTitle: String,
    val availabilityOnDescription: String,
    val availabilityOffDescription: String,
    val availabilityError: String,
    val ratingsReceived: String,
    val ratingsCount: (Int) -> String,
    val ratingContentDescription: (Float) -> String,
    val logout: String,
    val visitorHeadline: String,
    val visitorFeatureSports: String,
    val visitorFeatureConnections: String,
    val visitorFeatureYou: String,
    val visitorCta: String,
    val availableUntilTonightLabel: String,
    val sportsPreferenceTitle: String,
    val sportsPreferenceError: String,
    val nextMatchSection: String,
    val fallbackAccountName: String,
    val myMatchesMenuLabel: String,
    val aboutMenuLabel: String,
)

internal val playerProfileStringsPt =
    PlayerProfileStrings(
        title = "Meu perfil",
        loadingLabel = "Carregando seu perfil…",
        statsMatches = "Partidas",
        statsParticipated = "Presenças",
        statsReviews = "Avaliações",
        statsRating = "Nota média",
        notificationsContentDescription = "Notificações",
        loadingError = "Erro ao carregar perfil.",
        availabilityTitle = "Estou disponível para jogar",
        availabilityOnDescription = "Você recebe aviso quando abrir partida perto de você.",
        availabilityOffDescription = "Você não recebe aviso de partida nova.",
        availabilityError = "Não foi possível mudar sua disponibilidade. Tente de novo.",
        ratingsReceived = "Avaliações recebidas",
        ratingsCount = { n -> if (n == 1) "1 avaliação" else "$n avaliações" },
        ratingContentDescription = { value -> "Nota $value de 5" },
        logout = "Sair da conta",
        visitorHeadline = "Conectando pessoas através do esporte.",
        visitorFeatureSports = "Mais esportes.",
        visitorFeatureConnections = "Mais conexões.",
        visitorFeatureYou = "Mais você.",
        visitorCta = "Entrar",
        availableUntilTonightLabel = "Só por hoje",
        sportsPreferenceTitle = "Esportes que eu jogo",
        sportsPreferenceError = "Não foi possível salvar seus esportes. Tente de novo.",
        nextMatchSection = "Próxima partida",
        fallbackAccountName = "Jogador",
        myMatchesMenuLabel = "Minhas partidas",
        aboutMenuLabel = "Sobre",
    )

internal val playerProfileStringsEn =
    PlayerProfileStrings(
        title = "My profile",
        loadingLabel = "Loading your profile…",
        statsMatches = "Matches",
        statsParticipated = "Attendance",
        statsReviews = "Reviews",
        statsRating = "Rating",
        notificationsContentDescription = "Notifications",
        loadingError = "Error loading profile.",
        availabilityTitle = "I'm available to play",
        availabilityOnDescription = "You'll be notified when a match opens near you.",
        availabilityOffDescription = "You won't be notified about new matches.",
        availabilityError = "Could not change your availability. Please try again.",
        ratingsReceived = "Ratings received",
        ratingsCount = { n -> if (n == 1) "1 rating" else "$n ratings" },
        ratingContentDescription = { value -> "Rated $value out of 5" },
        logout = "Log out",
        visitorHeadline = "Connecting people through sport.",
        visitorFeatureSports = "More sports.",
        visitorFeatureConnections = "More connections.",
        visitorFeatureYou = "More you.",
        visitorCta = "Sign in",
        availableUntilTonightLabel = "Just for today",
        sportsPreferenceTitle = "Sports I play",
        sportsPreferenceError = "Couldn't save your sports. Please try again.",
        nextMatchSection = "Next match",
        fallbackAccountName = "Player",
        myMatchesMenuLabel = "My matches",
        aboutMenuLabel = "About",
    )
