package com.walcker.identity.strings

internal data class PaywallStrings(
    val title: String,
    /** Nome acessível do botão voltar da barra de topo. */
    val back: String,
    val headline: String,
    val description: String,
    val proHeadline: String,
    val proDescription: String,
    val changePlanButton: String,
    val manageSubscriptionButton: String,
    val manageSubscriptionUnavailable: String,
    val restoreButton: String,
    val purchaseButton: String,
    val purchaseLoadingButton: String,
    val restoreLoadingButton: String,
    val retryButton: String,
    val loadingLabel: String,
    val emptyState: String,
    val restoreSuccessMessage: String,
    val restoreNoPurchasesMessage: String,
    val purchaseCancelledMessage: String,
    val networkError: String,
    val productUnavailableError: String,
    val billingUnavailableError: String,
    val missingProAccessError: String,
    val genericError: String,
    val selectedPlanLabel: String,
    val selectPlanHint: String,
    val backButton: String,
    val subscriptionInfoTitle: String,
    val priceLabel: String,
    val periodLabel: String,
    val autoRenewLabel: String,
    val autoRenewDescription: String,
    val billingExplanation: String,
    val termsOfUseLabel: String,
    val privacyPolicyLabel: String,
    val monthlyPeriodLabel: String,
    val yearlyPeriodLabel: String,
)

// ATENÇÃO: os benefícios do Match Pro ainda não estão definidos (decisão D27 —
// assinatura e limite de plano estão fora do MVP). O texto abaixo é deliberadamente
// genérico: o anterior era do Lexis e prometia números Strong's e versículos
// favoritos, coisas que este produto não tem. Prometer benefício que não existe
// numa tela de cobrança é pior do que não detalhar. Trocar quando D27 for decidida.
internal val paywallStringsEn = PaywallStrings(
    title = "Match Pro",
    back = "Back",
    headline = "Support Match with Pro",
    description = "Match Pro keeps the app running and gets you first access to what comes next. You can cancel any time from the store.",
    proHeadline = "You are PRO",
    proDescription = "Your Match Pro benefits are active. You can switch plans or manage your subscription on the store.",
    changePlanButton = "Change plan",
    manageSubscriptionButton = "Manage subscription",
    manageSubscriptionUnavailable = "Subscription management is unavailable right now.",
    restoreButton = "Restore purchases",
    purchaseButton = "Continue",
    purchaseLoadingButton = "Processing...",
    restoreLoadingButton = "Restoring...",
    retryButton = "Try again",
    loadingLabel = "Loading plans...",
    emptyState = "No plans are available right now.",
    restoreSuccessMessage = "Purchases restored.",
    restoreNoPurchasesMessage = "No active purchases were found to restore.",
    purchaseCancelledMessage = "Purchase cancelled.",
    networkError = "Unable to reach billing right now.",
    productUnavailableError = "This plan is no longer available.",
    billingUnavailableError = "Billing is unavailable in the current app setup.",
    missingProAccessError = "Your purchase finished, but Pro access is not active yet.",
    genericError = "Unable to complete this action right now.",
    selectedPlanLabel = "Selected",
    selectPlanHint = "Tap to select",
    backButton = "Back",
    subscriptionInfoTitle = "Subscription information",
    priceLabel = "Price",
    periodLabel = "Period",
    autoRenewLabel = "Renewal",
    autoRenewDescription = "Automatically renews until canceled.",
    billingExplanation = "Subscription renews automatically at the end of each billing period unless canceled before renewal.",
    termsOfUseLabel = "Terms of Use",
    privacyPolicyLabel = "Privacy Policy",
    monthlyPeriodLabel = "Monthly",
    yearlyPeriodLabel = "Yearly",
)

internal val paywallStringsPt = PaywallStrings(
    title = "Match Pro",
    back = "Voltar",
    headline = "Apoie o Match com o Pro",
    description = "O Match Pro mantém o app de pé e te dá acesso antecipado ao que vem por aí. Dá para cancelar quando quiser, direto na loja.",
    proHeadline = "Você é PRO",
    proDescription = "Seus benefícios do Match Pro estão ativos. Você pode trocar de plano ou gerenciar a assinatura na loja.",
    changePlanButton = "Mudar de plano",
    manageSubscriptionButton = "Gerenciar assinatura",
    manageSubscriptionUnavailable = "Gerenciamento da assinatura indisponível no momento.",
    restoreButton = "Restaurar compras",
    purchaseButton = "Continuar",
    purchaseLoadingButton = "Processando...",
    restoreLoadingButton = "Restaurando...",
    retryButton = "Tentar novamente",
    loadingLabel = "Carregando planos...",
    emptyState = "Nenhum plano está disponível agora.",
    restoreSuccessMessage = "Compras restauradas.",
    restoreNoPurchasesMessage = "Nenhuma compra ativa foi encontrada para restaurar.",
    purchaseCancelledMessage = "Compra cancelada.",
    networkError = "Não foi possível acessar o billing agora.",
    productUnavailableError = "Esse plano não está mais disponível.",
    billingUnavailableError = "O billing não está disponível na configuração atual do app.",
    missingProAccessError = "A compra foi concluída, mas o acesso Pro ainda não foi ativado.",
    genericError = "Não foi possível concluir essa ação agora.",
    selectedPlanLabel = "Selecionado",
    selectPlanHint = "Toque para selecionar",
    backButton = "Voltar",
    subscriptionInfoTitle = "Informações da assinatura",
    priceLabel = "Preço",
    periodLabel = "Período",
    autoRenewLabel = "Renovação",
    autoRenewDescription = "Renovação automática até cancelamento.",
    billingExplanation = "A assinatura é renovada automaticamente ao fim de cada período, a menos que seja cancelada antes da renovação.",
    termsOfUseLabel = "Termos de uso",
    privacyPolicyLabel = "Política de privacidade",
    monthlyPeriodLabel = "Mensal",
    yearlyPeriodLabel = "Anual",
)

