package com.walcker.identity.strings

internal data class ProfileStrings(
    val title: String,
    val fallbackAccountName: String,
    val proStatusLabel: String,
    val proStatusDescription: String,
    val freeStatusLabel: String,
    val freeStatusDescription: String,
    val subscribeProButton: String,
    val changePlanButton: String,
    val manageSubscriptionButton: String,
    val manageSubscriptionUnavailable: String,
    val restorePurchasesButton: String,
    val restorePurchasesLoadingButton: String,
    val restorePurchasesSuccess: String,
    val restorePurchasesNoneFound: String,
    val restorePurchasesError: String,
    val deleteAccountButton: String,
    val deleteAccountLoadingButton: String,
    val deleteAccountConfirmationTitle: String,
    val deleteAccountConfirmationMessage: String,
    val deleteAccountConfirmationButton: String,
    val deleteAccountCancelButton: String,
    val deleteAccountRequiresRecentLogin: String,
    val deleteAccountError: String,
    val signOutButton: String,
    val signOutLoadingButton: String,
    val signOutError: String,
    val languageLabel: String,
    val languagePortuguese: String,
    val languageEnglish: String,
)

internal val profileStringsEn = ProfileStrings(
    title = "Profile",
    fallbackAccountName = "Match account",
    proStatusLabel = "You are PRO",
    proStatusDescription = "Your PRO benefits are active on this account.",
    freeStatusLabel = "Free plan",
    freeStatusDescription = "Unlock the full Match experience with PRO.",
    subscribeProButton = "Subscribe to PRO",
    changePlanButton = "Change plan",
    manageSubscriptionButton = "Manage subscription",
    manageSubscriptionUnavailable = "Subscription management is unavailable right now.",
    restorePurchasesButton = "Restore purchases",
    restorePurchasesLoadingButton = "Restoring purchases...",
    restorePurchasesSuccess = "Purchases restored.",
    restorePurchasesNoneFound = "No active purchases were found to restore.",
    restorePurchasesError = "Could not restore purchases",
    deleteAccountButton = "Delete account",
    deleteAccountLoadingButton = "Deleting account...",
    deleteAccountConfirmationTitle = "Delete account?",
    deleteAccountConfirmationMessage = "This permanently removes your Match account and its saved data. Active subscriptions must be cancelled through the app store.",
    deleteAccountConfirmationButton = "Delete permanently",
    deleteAccountCancelButton = "Cancel",
    deleteAccountRequiresRecentLogin = "For your security, sign in again and retry account deletion.",
    deleteAccountError = "Could not delete account",
    signOutButton = "Sign out",
    signOutLoadingButton = "Signing out...",
    signOutError = "Could not sign out",
    languageLabel = "Language",
    languagePortuguese = "Portuguese (Português)",
    languageEnglish = "English",
)

internal val profileStringsPt = ProfileStrings(
    title = "Perfil",
    fallbackAccountName = "Conta Match",
    proStatusLabel = "Você é PRO",
    proStatusDescription = "Os benefícios do seu plano PRO estão ativos nesta conta.",
    freeStatusLabel = "Plano gratuito",
    freeStatusDescription = "Desbloqueie a experiência completa do Match com o PRO.",
    subscribeProButton = "Assinar PRO",
    changePlanButton = "Mudar de plano",
    manageSubscriptionButton = "Gerenciar assinatura",
    manageSubscriptionUnavailable = "Gerenciamento da assinatura indisponível no momento.",
    restorePurchasesButton = "Restaurar compras",
    restorePurchasesLoadingButton = "Restaurando compras...",
    restorePurchasesSuccess = "Compras restauradas.",
    restorePurchasesNoneFound = "Nenhuma compra ativa foi encontrada para restaurar.",
    restorePurchasesError = "Não foi possível restaurar as compras",
    deleteAccountButton = "Excluir conta",
    deleteAccountLoadingButton = "Excluindo conta...",
    deleteAccountConfirmationTitle = "Excluir conta?",
    deleteAccountConfirmationMessage = "Esta ação remove permanentemente sua conta Match e seus dados salvos. Assinaturas ativas devem ser canceladas pela loja.",
    deleteAccountConfirmationButton = "Excluir permanentemente",
    deleteAccountCancelButton = "Cancelar",
    deleteAccountRequiresRecentLogin = "Para sua segurança, entre novamente e tente excluir a conta outra vez.",
    deleteAccountError = "Não foi possível excluir a conta",
    signOutButton = "Sair",
    signOutLoadingButton = "Saindo...",
    signOutError = "Não foi possível sair",
    languageLabel = "Idioma",
    languagePortuguese = "Português",
    languageEnglish = "English",
)
