package com.walcker.identity.strings

internal data class SignUpStrings(
    val title: String,
    val subtitle: String,
    val back: String,
    val fullNameLabel: String,
    val emailLabel: String,
    val passwordLabel: String,
    val passwordHelper: String,
    val confirmPasswordLabel: String,
    val showPassword: String,
    val hidePassword: String,
    val submitButton: String,
    val submitLoadingButton: String,
    val socialDivider: String,
    val googleButton: String,
    val appleButton: String,
    val loginButton: String,
    val blankFieldsError: String,
    val passwordMismatchError: String,
    val signUpError: String,
)

internal val signUpStringsEn =
    SignUpStrings(
        title = "Create account",
        subtitle = "Create your account and join the community",
        back = "Back",
        fullNameLabel = "Full name",
        emailLabel = "E-mail",
        passwordLabel = "Password",
        passwordHelper = "At least 6 characters",
        confirmPasswordLabel = "Confirm password",
        showPassword = "Show password",
        hidePassword = "Hide password",
        submitButton = "Create account",
        submitLoadingButton = "Creating account...",
        socialDivider = "or",
        googleButton = "Continue with Google",
        appleButton = "Continue with Apple",
        loginButton = "Already have an account? Sign in",
        blankFieldsError = "Fill in name, e-mail, password and password confirmation",
        passwordMismatchError = "Passwords do not match",
        signUpError = "Could not create the account",
    )

internal val signUpStringsPt =
    SignUpStrings(
        title = "Criar conta",
        subtitle = "Crie sua conta e faça parte da comunidade",
        back = "Voltar",
        fullNameLabel = "Nome completo",
        emailLabel = "E-mail",
        passwordLabel = "Senha",
        passwordHelper = "No mínimo 6 caracteres",
        confirmPasswordLabel = "Confirmar senha",
        showPassword = "Mostrar senha",
        hidePassword = "Esconder senha",
        submitButton = "Criar conta",
        submitLoadingButton = "Criando conta...",
        socialDivider = "ou",
        googleButton = "Continuar com Google",
        appleButton = "Continuar com Apple",
        loginButton = "Já tem uma conta? Entrar",
        blankFieldsError = "Preencha nome, e-mail, senha e confirmação de senha",
        passwordMismatchError = "As senhas não coincidem",
        signUpError = "Não foi possível criar a conta",
    )
