package com.walcker.identity.strings

internal data class VerificationStrings(
    val emailTitle: String,
    val emailSubtitle: String,
    val emailSentLead: String,
    val emailSentAction: String,
    val emailSpamHint: String,
    val emailConfirmedButton: String,
    val emailResendButton: String,
    val emailSent: String,
    val emailNotConfirmedYet: String,
    val phoneTitle: String,
    val phoneSubtitle: String,
    val countryLabel: String,
    val countryPickerTitle: String,
    val countrySearchLabel: String,
    val phoneNumberLabel: String,
    val sendCodeButton: String,
    val codeSentTo: (String) -> String,
    val codeLabel: String,
    val confirmCodeButton: String,
    val resendCodeButton: String,
    val changeNumberButton: String,
    val resendIn: (Int) -> String,
    val logoutButton: String,
    val errorTooManyRequests: String,
    val errorNetwork: String,
    val errorInvalidPhoneNumber: String,
    val errorInvalidCode: String,
    val errorCodeExpired: String,
    val errorPhoneAlreadyInUse: String,
    val errorIncompleteCode: String,
    val errorGeneric: String,
    val changePhoneTitle: String,
    val changePhoneSubtitle: String,
    val back: String,
    val errorSamePhoneNumber: String,
    val errorRequiresRecentLogin: String,
)

internal val verificationStringsPt =
    VerificationStrings(
        emailTitle = "Confirme seu e-mail",
        emailSubtitle = "Falta pouco para você começar a jogar",
        emailSentLead = "Enviamos um link de confirmação para",
        emailSentAction = "Abra o e-mail e toque no link. Depois volte para cá.",
        emailSpamHint = "Não chegou? Confira a caixa de spam.",
        emailConfirmedButton = "Já confirmei",
        emailResendButton = "Reenviar e-mail",
        emailSent = "E-mail enviado.",
        emailNotConfirmedYet = "Ainda não recebemos a confirmação. Abra o link no seu e-mail.",
        phoneTitle = "Confirme seu celular",
        phoneSubtitle = "Vamos enviar um código por SMS",
        countryLabel = "País",
        countryPickerTitle = "Escolha o país",
        countrySearchLabel = "Buscar país",
        phoneNumberLabel = "Número do celular",
        sendCodeButton = "Enviar código",
        codeSentTo = { phone -> "Enviamos um código de 6 dígitos para $phone." },
        codeLabel = "Código de 6 dígitos",
        confirmCodeButton = "Confirmar",
        resendCodeButton = "Reenviar código",
        changeNumberButton = "Trocar número",
        resendIn = { seconds -> "Reenviar em ${seconds}s" },
        logoutButton = "Sair da conta",
        errorTooManyRequests = "Muitas tentativas. Espere alguns minutos e tente de novo.",
        errorNetwork = "Sem conexão. Confira a internet e tente de novo.",
        errorInvalidPhoneNumber = "Confira o número e o país selecionado.",
        errorInvalidCode = "Código incorreto. Confira o SMS e tente de novo.",
        errorCodeExpired = "O código expirou. Peça um novo.",
        errorPhoneAlreadyInUse = "Esse número já está em uso em outra conta.",
        errorIncompleteCode = "Digite os 6 dígitos do código.",
        errorGeneric = "Algo deu errado. Tente de novo.",
        changePhoneTitle = "Trocar celular",
        changePhoneSubtitle = "Vamos confirmar o número novo por SMS",
        back = "Voltar",
        errorSamePhoneNumber = "Esse já é o seu número.",
        errorRequiresRecentLogin = "Por segurança, saia e entre de novo antes de trocar o número.",
    )

internal val verificationStringsEn =
    VerificationStrings(
        emailTitle = "Confirm your e-mail",
        emailSubtitle = "You're almost ready to play",
        emailSentLead = "We sent a confirmation link to",
        emailSentAction = "Open the e-mail and tap the link. Then come back here.",
        emailSpamHint = "Didn't get it? Check your spam folder.",
        emailConfirmedButton = "I've confirmed",
        emailResendButton = "Resend e-mail",
        emailSent = "E-mail sent.",
        emailNotConfirmedYet = "We haven't received the confirmation yet. Open the link in your e-mail.",
        phoneTitle = "Confirm your phone",
        phoneSubtitle = "We'll text you a code",
        countryLabel = "Country",
        countryPickerTitle = "Choose your country",
        countrySearchLabel = "Search country",
        phoneNumberLabel = "Mobile number",
        sendCodeButton = "Send code",
        codeSentTo = { phone -> "We sent a 6-digit code to $phone." },
        codeLabel = "6-digit code",
        confirmCodeButton = "Confirm",
        resendCodeButton = "Resend code",
        changeNumberButton = "Change number",
        resendIn = { seconds -> "Resend in ${seconds}s" },
        logoutButton = "Log out",
        errorTooManyRequests = "Too many attempts. Wait a few minutes and try again.",
        errorNetwork = "No connection. Check your internet and try again.",
        errorInvalidPhoneNumber = "Check the number and the selected country.",
        errorInvalidCode = "Wrong code. Check the SMS and try again.",
        errorCodeExpired = "The code expired. Request a new one.",
        errorPhoneAlreadyInUse = "This number is already used by another account.",
        errorIncompleteCode = "Enter all 6 digits of the code.",
        errorGeneric = "Something went wrong. Please try again.",
        changePhoneTitle = "Change phone number",
        changePhoneSubtitle = "We'll confirm the new number by SMS",
        back = "Back",
        errorSamePhoneNumber = "This is already your number.",
        errorRequiresRecentLogin = "For security, log out and sign in again before changing your number.",
    )
